// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_zHLyrBirPMB2wyODf5yYihwQRnVTZQc',
    appId: '1:1027682286218:web:33e4ed6e8a74c00f228b73',
    messagingSenderId: '1027682286218',
    projectId: 'snapameal-cabc7',
    authDomain: 'snapameal-cabc7.firebaseapp.com',
    storageBucket: 'snapameal-cabc7.firebasestorage.app',
    measurementId: 'G-8VYTJ2E0VF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNYK0YFNBzXqoerc4BEqhdhBfK4lXMRTU',
    appId: '1:1027682286218:android:70a64e4cedffc1f0228b73',
    messagingSenderId: '1027682286218',
    projectId: 'snapameal-cabc7',
    storageBucket: 'snapameal-cabc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOhpbXKnfVDmK0cXVnd2myHCAyk8b9yIE',
    appId: '1:1027682286218:ios:8ecd7ac9018e7506228b73',
    messagingSenderId: '1027682286218',
    projectId: 'snapameal-cabc7',
    storageBucket: 'snapameal-cabc7.firebasestorage.app',
    iosClientId: '1027682286218-qbir9hfghc3mi8j702tu08h6vnn52aji.apps.googleusercontent.com',
    iosBundleId: 'com.example.snapconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOhpbXKnfVDmK0cXVnd2myHCAyk8b9yIE',
    appId: '1:1027682286218:ios:8ecd7ac9018e7506228b73',
    messagingSenderId: '1027682286218',
    projectId: 'snapameal-cabc7',
    storageBucket: 'snapameal-cabc7.firebasestorage.app',
    iosClientId: '1027682286218-qbir9hfghc3mi8j702tu08h6vnn52aji.apps.googleusercontent.com',
    iosBundleId: 'com.example.snapconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_zHLyrBirPMB2wyODf5yYihwQRnVTZQc',
    appId: '1:1027682286218:web:06d019bc81e5c1f4228b73',
    messagingSenderId: '1027682286218',
    projectId: 'snapameal-cabc7',
    authDomain: 'snapameal-cabc7.firebaseapp.com',
    storageBucket: 'snapameal-cabc7.firebasestorage.app',
    measurementId: 'G-RV8KQS1EHZ',
  );

}